// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCMdKTsQfHRw-aRkdDizC0Vqy66Ly3IWZg',
    appId: '1:804410762246:web:832bfdf6a710484d790f87',
    messagingSenderId: '804410762246',
    projectId: 'ravenry',
    authDomain: 'ravenry.firebaseapp.com',
    storageBucket: 'ravenry.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBNfzdNLDM7Ar7X1QvXGkOlQeJwm1h4-1U',
    appId: '1:804410762246:android:849a932d57a72a5b790f87',
    messagingSenderId: '804410762246',
    projectId: 'ravenry',
    storageBucket: 'ravenry.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBUO9Z3FV9i8ducvmp8XwSXfORZ66beyxo',
    appId: '1:804410762246:ios:5da56c795506dc69790f87',
    messagingSenderId: '804410762246',
    projectId: 'ravenry',
    storageBucket: 'ravenry.appspot.com',
    iosClientId:
        '804410762246-jghsfg8cf9hvpi84o03fouc7d1r03r5k.apps.googleusercontent.com',
    iosBundleId: 'org.hackndev.ravenry',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBUO9Z3FV9i8ducvmp8XwSXfORZ66beyxo',
    appId: '1:804410762246:ios:5da56c795506dc69790f87',
    messagingSenderId: '804410762246',
    projectId: 'ravenry',
    storageBucket: 'ravenry.appspot.com',
    iosClientId:
        '804410762246-jghsfg8cf9hvpi84o03fouc7d1r03r5k.apps.googleusercontent.com',
    iosBundleId: 'org.hackndev.ravenry',
  );
}
